fix: turbo caching and conditional prebuild

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -22,7 +22,7 @@ jobs:
           fetch-depth: 0
 
       - name: Setup GitHub Actions caching for Turbo
-        uses: dtinth/setup-github-actions-caching-for-turbo@v1
+        uses: rharkor/caching-for-turbo@v1.8
 
       - name: Setup pnpm
         uses: pnpm/action-setup@v4
@@ -60,6 +60,23 @@ jobs:
       - name: Run Type Check and Format Check
         run: pnpm turbo typecheck format:check lint ${{ steps.get-turbo-filter.outputs.TURBO_FILTER }}
 
+      - name: Check for changes in mobile apps
+        id: check-mobile-changes
+        run: |
+          # `turbo-ignore` exits with 0 if workspace didn't change, and a non-zero (error) if it did change
+          # evaluate exit code to output true/false if packaged changed.
+          run: |
+            # disable "exit on failure"
+            set +e
+            npx -y turbo-ignore @client/mobile --fallback ${{ github.event.pull_request.base.sha }}
+            if [ $? -eq 0 ]
+            then
+              echo "MOBILE_CHANGES=false" >> $GITHUB_OUTPUT
+            else
+              echo "MOBILE_CHANGES=true" >> $GITHUB_OUTPUT
+            fi
+
       - name: Run Prebuild
+        if: ${{ github.event_name == 'push' || steps.check-mobile-changes.outputs.MOBILE_CHANGES == 'true' }}
         working-directory: apps-client/mobile
         run: npx expo prebuild
